Added Status check for mcg-ms-console pod
red-hat-storage/mcg-osd-deployer pull request #76
Opened 2022-08-09 09:32 UTC by achouhan09

Signed-off-by: Aayush Chouhan <achouhan@redhat.com>

2022-08-09 14:56 UTC, naveenpaul1 approved these changes
lgtm

2022-08-10 05:59 UTC, naveenpaul1 commented
@achouhan09 please fix lint error

2022-08-10 07:15 UTC, rexagod commented
/approve

2022-08-10 07:18 UTC, rexagod requested changes

2022-08-10 07:18 UTC, rexagod commented on controllers/managedmcg_controller.go
>  }
I'd suggest breaking off the Noobaa, Alertmanager, Prometheus, and Console status updation parts into their own functions, and calling them here to reduce the cognitive complexity: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/red-hat-storage_mcg-osd-deployer/76/pull-ci-red-hat-storage-mcg-osd-deployer-main-lint/1556936379416449024#1:build-log.txt%3A24.

2022-08-10 13:50 UTC, rexagod requested changes
- ~~Please replace https://github.com/achouhan09/mcg-osd-deployer/blob/mcg-console-status/controllers/managedmcg_controller.go#L652-L656 with `CheckReplicaStatus`.~~
- Please replace `https://github.com/achouhan09/mcg-osd-deployer/blob/mcg-console-status/controllers/managedmcg_controller.go#L638` with `s/Nooba/Noobaa/g`.

2022-08-10 14:03 UTC, rexagod approved these changes
/lgtm

2022-08-10 14:10 UTC, merged